### ISSUE TITLE
[Ruby: turbine core] User friendly connector config

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#17]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Turbine-Ruby-Implementation-Plan-ba3f655e7eea4697bf27d3fbf2fa45d3)

## Context 

Turbine Ruby needs a user friendly way to add connector configs. Currently the config is set [here](https://github.com/meroxa/turbine-core-grpc/blob/ah/ruby/lib/ruby/turbine/lib/turbine.rb#L57). The class of the config is generated by proto, which means that when someone is building a turbine app, they have to use the proto directly to register connector config. We want to add an intermediate layer here, most probably a ruby hash. 

## Acceptance 

- [ ] Turbine Ruby app has a user friendly way to register connector configs

**Comment by jmar910** [comment]
Closed by https://github.com/meroxa/turbine-core/pull/24
