### ISSUE TITLE
[Ruby M2: ruby] Init command sets up app folder

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#28]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Turbine-Ruby-Implementation-Plan-ba3f655e7eea4697bf27d3fbf2fa45d3)

## Context 

Add a cli command to Turbine Ruby that initializes and sets up an example app folder. This command will be used my the meroxa cli when running `meroxa apps init`.

## Acceptance 

- [x] Ruby cli command that creates a folder setup with git and an example app
- [x] Ensure that the created folder contains setup instructions for the new app

**Comment by jmar910** [comment]
Closed by https://github.com/meroxa/turbine-core/pull/55
