### ISSUE TITLE
[Ruby: turbine core] Publish Ruby gem

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#40]
## Context

Publish turbine ruby gem. 

## Acceptance 

- [x] Publish turbine ruby gem
- [x] Add instructions on how to release a new version

**Comment by jmar910** [comment]
Going to jot down the instructions here for now and we can move to notion but the publishing process is very simple

+ Update the turbine_rb version in turbine_rb/version.rb
+ Submit PR
+ Once PR is merged to `main` MAKE SURE TO PULL LATEST `main`
+ Make sure you are at gem root
+ `gem build` => outputs turbine_rb-x.x.x.gem file
+ `gem push turbine_rb-x.x.x.gem`
+ Rubygems will prompt for credentials, machine account credentials are in 1pass
+  Gem is now published!
