### ISSUE TITLE
[Ruby M2: ruby] Automate publishing of ruby gem 

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#45]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Turbine-Ruby-Implementation-Plan-ba3f655e7eea4697bf27d3fbf2fa45d3)

## Context 

Create a github action to automatically publish ruby gems 

## Acceptance 

- [ ] A github action that automatically publishes ruby gems

**Comment by raulb** [comment]
Assigning this to @jmar910 since he mentioned yesterday during planning he'd work on this one.

**Comment by jmar910** [comment]
Closed by #64 #65 #66
