### ISSUE TITLE
[Ruby M2: turbine core] Validate IR json blob with stream information

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#48]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Turbine-Ruby-Implementation-Plan-ba3f655e7eea4697bf27d3fbf2fa45d3)
- [IR support for different inputs to destination connectors](https://www.notion.so/Intermediate-Representation-to-Support-Different-Inputs-to-Destination-Connectors-ed49abffd9594189a84f5cbd6ff2b6cd)
- [Deployment spec for topologies](https://www.notion.so/meroxa/Deployment-Spec-for-Topologies-c6b1bb149f5949afa19ac15a2fb18bd7)

**Depends on**

- [x] https://github.com/meroxa/turbine-core/issues/47

## Context 

With the modification made to the IR spec to support different inputs to destination connectors, we need to update spec validations to account for the change. 

Ensure that two versions of IR are supported, one with the streams, the other without. 

## Acceptance 

- [ ] Create another spec version, and validate streams

**Comment by anna-cross** [comment]
Addressed in https://github.com/meroxa/turbine-core/pull/60
