### ISSUE TITLE
[Ruby M2: turbine core] Populate stream information

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#49]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Turbine-Ruby-Implementation-Plan-ba3f655e7eea4697bf27d3fbf2fa45d3)
- [IR support for different inputs to destination connectors](https://www.notion.so/Intermediate-Representation-to-Support-Different-Inputs-to-Destination-Connectors-ed49abffd9594189a84f5cbd6ff2b6cd)
- [Deployment spec for topologies](https://www.notion.so/meroxa/Deployment-Spec-for-Topologies-c6b1bb149f5949afa19ac15a2fb18bd7)

**Depends on**

- [x] https://github.com/meroxa/turbine-core/issues/48
- [ ] https://github.com/meroxa/turbine-core/issues/49

## Context 

With the modification made to the IR spec to support different inputs to destination connectors, we need to modify turbine-core to populate stream information into the collection object. 

## Acceptance 

- [ ] Turbine core tracks stream information and generates identifiers for connectors and functions

**Comment by anna-cross** [comment]
Addressed as part of https://github.com/meroxa/turbine-core/pull/63
