### ISSUE TITLE
[Env: turbine-core] Record server processing Environment information

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-core#80]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Environments-Turbine-Support-Implementation-Plan-8aa02e78eaec453ab6b47ff9d5c2a9ed)

**Depends on**

- [x] https://github.com/meroxa/turbine-core/issues/81

## Context 

Prior to generating an IR spec, the CLI needs a way to provide Environment information to the [record server](https://github.com/meroxa/turbine-core/blob/main/pkg/server/record.go). 

## Acceptance 

- [ ] The [record server](https://github.com/meroxa/turbine-core/blob/main/pkg/server/record.go) should collect Environment information before generating the IR spec. This information could be provided on the creation of a record server, on it's call to initialize, or as part of the [request to generate spec](https://github.com/meroxa/turbine-core/blob/790a595f9cd582e5b51cf61553c24b0dc8408cda/pkg/server/record.go#L179)
- [ ] Validation: ensure that if Environment is not common, then a spec cannot have a function present

**Comment by anna-cross** [comment]
We are no longer implementing environment changes on IR 

Please see: https://www.notion.so/meroxa/Environments-Turbine-Support-Implementation-Plan-8aa02e78eaec453ab6b47ff9d5c2a9ed#9949af41ad474e79b835be451b4e1cc6
